[package]
name = "uiko-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "uiko"
path = "src/main.rs"

[dependencies]
uiko-compiler = { path = "../uiko-compiler" }
uiko-core = { path = "../uiko-core" }
uiko-manifest = { path = "../uiko-manifest" }
uiko-project = { path = "../uiko-project" }

[lints]
workspace = true
