import { defineCatalog } from "@json-render/core";
import { defineRegistry } from "@json-render/vue";
import { schema } from "@json-render/vue/schema";
import { h } from "vue";
import { z } from "zod";

const stateValueSchema = z.union([z.string(), z.number().int(), z.null()]);

export const catalog = defineCatalog(schema, {
  components: {
    Stack: {
      props: z.object({
        uikoId: z.string(),
      }),
      description: "Vertical container generated by the uiko renderer adapter.",
    },
    Text: {
      props: z.object({
        uikoId: z.string(),
        value: z.string(),
      }),
      description: "Plain text. Upstream text is never interpreted as markup.",
    },
    Field: {
      props: z.object({
        uikoId: z.string(),
        label: z.string(),
        binding: z.string(),
        value: z.unknown(),
      }),
      description: "Label plus a value resolved from a compiled logical query.",
    },
    Table: {
      props: z.object({
        uikoId: z.string(),
        binding: z.string(),
        rows: z.array(z.unknown()),
      }),
      description: "Generic table over a compiled list binding.",
    },
    Select: {
      props: z.object({
        uikoId: z.string(),
        label: z.string(),
        state: z.string(),
        value: stateValueSchema,
        options: z.array(
          z.object({
            label: z.string(),
            value: stateValueSchema,
          }),
        ),
      }),
      description: "Select one scalar page-state value.",
    },
    Pagination: {
      props: z.object({
        uikoId: z.string(),
        state: z.string(),
        value: stateValueSchema,
        page: z.number().int().nullable(),
        pageSize: z.number().int().nullable(),
        total: z.number().int().nullable(),
      }),
      description: "Previous/Next control for one integer page-state value.",
    },
  },
  actions: {},
});

export const { registry } = defineRegistry(catalog, {
  components: {
    Stack: ({ props, children }) =>
      h(
        "section",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Stack",
        },
        children,
      ),
    Text: ({ props }) =>
      h(
        "p",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Text",
        },
        props.value,
      ),
    Field: ({ props }) =>
      h(
        "div",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Field",
          "data-uiko-binding": props.binding,
        },
        [
          h("strong", null, props.label),
          h("span", { "aria-live": "polite" }, formatValue(props.value)),
        ],
      ),
    Table: ({ props }) => renderTable(props.uikoId, props.binding, props.rows),
    Select: ({ props }) => {
      const selectedIndex = props.options.findIndex((option) =>
        stateValueEquals(option.value, props.value),
      );
      return h(
        "label",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Select",
          "data-uiko-state": props.state,
        },
        [
          h("span", null, props.label),
          h(
            "select",
            {
              "aria-label": props.label,
              value: String(selectedIndex >= 0 ? selectedIndex : 0),
              onChange: (event: Event) => {
                const target = event.target;
                if (!(target instanceof HTMLSelectElement)) {
                  return;
                }
                const option = props.options[Number(target.value)];
                if (option !== undefined) {
                  dispatchStateChange(props.state, option.value);
                }
              },
            },
            props.options.map((option, index) =>
              h("option", { value: String(index) }, option.label),
            ),
          ),
        ],
      );
    },
    Pagination: ({ props }) => {
      const currentPage =
        props.page ?? (typeof props.value === "number" ? props.value : 1);
      const previousDisabled = props.page === null || currentPage <= 1;
      const nextDisabled =
        props.page === null ||
        props.pageSize === null ||
        props.total === null ||
        currentPage * props.pageSize >= props.total;

      return h(
        "nav",
        {
          "aria-label": "Pagination",
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Pagination",
          "data-uiko-state": props.state,
        },
        [
          h(
            "button",
            {
              type: "button",
              disabled: previousDisabled,
              onClick: () => {
                if (!previousDisabled) {
                  dispatchStateChange(props.state, currentPage - 1);
                }
              },
            },
            "Previous",
          ),
          h("span", { "aria-live": "polite" }, `Page ${currentPage}`),
          h(
            "button",
            {
              type: "button",
              disabled: nextDisabled,
              onClick: () => {
                if (!nextDisabled) {
                  dispatchStateChange(props.state, currentPage + 1);
                }
              },
            },
            "Next",
          ),
        ],
      );
    },
  },
});

function renderTable(
  uikoId: string,
  binding: string,
  rows: unknown[],
): ReturnType<typeof h> {
  const records = rows.filter(isRecord);
  const columns = Array.from(
    new Set(records.flatMap((row) => Object.keys(row))),
  );

  return h(
    "table",
    {
      "data-uiko-id": uikoId,
      "data-uiko-kind": "Table",
      "data-uiko-binding": binding,
      "aria-label": binding,
    },
    [
      h(
        "thead",
        null,
        h(
          "tr",
          null,
          columns.map((column) => h("th", { scope: "col" }, column)),
        ),
      ),
      h(
        "tbody",
        null,
        records.map((row) =>
          h(
            "tr",
            null,
            columns.map((column) => h("td", null, formatValue(row[column]))),
          ),
        ),
      ),
    ],
  );
}

function dispatchStateChange(
  state: string,
  value: string | number | null,
): void {
  window.dispatchEvent(
    new CustomEvent("uiko-state-change", {
      detail: { state, value },
    }),
  );
}

function stateValueEquals(
  left: string | number | null,
  right: string | number | null,
): boolean {
  return left === right;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }
  if (typeof value === "string") {
    return value;
  }
  if (
    typeof value === "number" ||
    typeof value === "boolean" ||
    typeof value === "bigint"
  ) {
    return String(value);
  }
  return JSON.stringify(value);
}
