import { defineCatalog } from "@json-render/core";
import { defineRegistry } from "@json-render/vue";
import { schema } from "@json-render/vue/schema";
import { h } from "vue";
import { z } from "zod";

export const catalog = defineCatalog(schema, {
  components: {
    Stack: {
      props: z.object({
        uikoId: z.string(),
      }),
      description: "Vertical container generated by the uiko renderer adapter.",
    },
    Text: {
      props: z.object({
        uikoId: z.string(),
        value: z.string(),
      }),
      description: "Plain text. Upstream text is never interpreted as markup.",
    },
    Field: {
      props: z.object({
        uikoId: z.string(),
        label: z.string(),
        binding: z.string(),
        value: z.unknown(),
      }),
      description: "Label plus a value resolved from a compiled logical query.",
    },
    Table: {
      props: z.object({
        uikoId: z.string(),
        binding: z.string(),
        rows: z.array(z.unknown()),
      }),
      description: "Generic table over a compiled list binding.",
    },
  },
  actions: {},
});

export const { registry } = defineRegistry(catalog, {
  components: {
    Stack: ({ props, children }) =>
      h(
        "section",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Stack",
        },
        children,
      ),
    Text: ({ props }) =>
      h(
        "p",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Text",
        },
        props.value,
      ),
    Field: ({ props }) =>
      h(
        "div",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Field",
          "data-uiko-binding": props.binding,
        },
        [
          h("strong", null, props.label),
          h("span", { "aria-live": "polite" }, formatValue(props.value)),
        ],
      ),
    Table: ({ props }) => renderTable(props.uikoId, props.binding, props.rows),
  },
});

function renderTable(
  uikoId: string,
  binding: string,
  rows: unknown[],
): ReturnType<typeof h> {
  const records = rows.filter(isRecord);
  const columns = Array.from(
    new Set(records.flatMap((row) => Object.keys(row))),
  );

  return h(
    "table",
    {
      "data-uiko-id": uikoId,
      "data-uiko-kind": "Table",
      "data-uiko-binding": binding,
      "aria-label": binding,
    },
    [
      h(
        "thead",
        null,
        h(
          "tr",
          null,
          columns.map((column) => h("th", { scope: "col" }, column)),
        ),
      ),
      h(
        "tbody",
        null,
        records.map((row) =>
          h(
            "tr",
            null,
            columns.map((column) => h("td", null, formatValue(row[column]))),
          ),
        ),
      ),
    ],
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }
  if (typeof value === "string") {
    return value;
  }
  if (
    typeof value === "number" ||
    typeof value === "boolean" ||
    typeof value === "bigint"
  ) {
    return String(value);
  }
  return JSON.stringify(value);
}
