import { defineCatalog } from "@json-render/core";
import { defineRegistry } from "@json-render/vue";
import { schema } from "@json-render/vue/schema";
import { h } from "vue";
import { z } from "zod";

export const catalog = defineCatalog(schema, {
  components: {
    Stack: {
      props: z.object({
        uikoId: z.string(),
      }),
      description: "Vertical container generated by the uiko renderer adapter.",
    },
    Text: {
      props: z.object({
        uikoId: z.string(),
        value: z.string(),
      }),
      description: "Plain text. Upstream text is never interpreted as markup.",
    },
    Field: {
      props: z.object({
        uikoId: z.string(),
        label: z.string(),
        binding: z.string(),
      }),
      description: "Label plus a compiled data binding. Data resolution arrives in the OpenAPI read slice.",
    },
    Table: {
      props: z.object({
        uikoId: z.string(),
        binding: z.string(),
      }),
      description: "Compiled list binding shell. Projection and pagination arrive in the OpenAPI read slice.",
    },
  },
  actions: {},
});

export const { registry } = defineRegistry(catalog, {
  components: {
    Stack: ({ props, children }) =>
      h(
        "section",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Stack",
        },
        children,
      ),
    Text: ({ props }) =>
      h(
        "p",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Text",
        },
        props.value,
      ),
    Field: ({ props }) =>
      h(
        "div",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Field",
          "data-uiko-binding": props.binding,
        },
        [
          h("strong", null, props.label),
          h("span", { "aria-live": "polite" }, ""),
        ],
      ),
    Table: ({ props }) =>
      h(
        "table",
        {
          "data-uiko-id": props.uikoId,
          "data-uiko-kind": "Table",
          "data-uiko-binding": props.binding,
          "aria-label": props.binding,
        },
        [h("tbody")],
      ),
  },
});
