[package]
name = "uiko-diff"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
uiko-capabilities = { path = "../uiko-capabilities" }
uiko-core = { path = "../uiko-core" }

[dev-dependencies]
uiko-compiler = { path = "../uiko-compiler" }
uiko-project = { path = "../uiko-project" }
uiko-source = { path = "../uiko-source" }
uiko-source-jsonc = { path = "../uiko-source-jsonc" }

[lints]
workspace = true
